//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public string CouponCode { get; set; }
        public string Description { get; set; }
        public decimal Discount { get; set; }
    }
}
