//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Data;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public int RoleID { get; set; }
    
        public virtual Role Role { get; set; }
        public string getRole()
        {
            SqlConnection con = DatabaseConnection.Conecting_to_database();
            int a = Convert.ToInt32(RoleID);
            using (SqlCommand command = new SqlCommand("select name from Roles r join Users u on r.RoleID=u.RoleID where UserID='" + a + "'", con))
            {
                SqlDataReader r = command.ExecuteReader();
                string name = "";
                while (r.Read())
                {
                    name = r.GetValue(0).ToString();
                }
                return name;
            }
        }
    }
}
